#! /bin/sh
# this will run just before making a commit
/bin/sh "$(git rev-parse --show-toplevel)/.tracking/record.sh" commit # add commit entry
git add "$(git rev-parse --show-toplevel)/.tracking" # add the entry to the current commit
